import assert from 'node:assert/strict';
import test from 'node:test';

test('publishes the framework-independent runtime entry', async () => {
  const entry = await import('../dist/index.js');

  assert.deepEqual(Object.keys(entry), [
    'CmAccordionController',
    'CmAdminLayoutController',
    'CmCheckboxController',
    'CmCommandPaletteController',
    'CmDataTableController',
    'CmDatePickerController',
    'CmDialogController',
    'CmDrawerController',
    'CmDropdownController',
    'CmInputController',
    'CmMenuBarController',
    'CmMenuController',
    'CmNavMenuController',
    'CmPopoverController',
    'CmRuntime',
    'CmSelectController',
    'CmSetupLayoutController',
    'CmStepperController',
    'CmTabsController',
    'CmTooltipController',
    'createCmAccordionController',
    'createCmAdminLayoutController',
    'createCmCheckboxController',
    'createCmCommandPaletteController',
    'createCmDataTableController',
    'createCmDatePickerController',
    'createCmDialogController',
    'createCmDrawerController',
    'createCmDropdownController',
    'createCmEvent',
    'createCmInputController',
    'createCmMenuBarController',
    'createCmMenuController',
    'createCmNavMenuController',
    'createCmPopoverController',
    'createCmSelectController',
    'createCmSetupLayoutController',
    'createCmStepperController',
    'createCmTabsController',
    'createCmTooltipController',
    'dispatchCmEvent',
  ]);
});
